name: ESP32 Hardware Robot Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hardware-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Python
        run: |
          "C:\Users\a7577\AppData\Local\Programs\Python\Python314\python.exe" --version

      - name: Install packages
        run: |
          "C:\Users\a7577\AppData\Local\Programs\Python\Python314\python.exe" -m pip install robotframework
          "C:\Users\a7577\AppData\Local\Programs\Python\Python314\python.exe" -m pip install pyserial

      - name: Run Robot Test
        run: |
          "C:\Users\a7577\AppData\Local\Programs\Python\Python314\Scripts\robot.exe" test.robot
